### PR TITLE
Another PR for test tracking

### PR DESCRIPTION
**Pull request by TheKevJames**
See #59

### CODE REVIEW

**Comment by TheKevJames** [comment]
Well fuck, looks like master is broken on travis, but only after a rerun. Could be related to travis changing their infrastructure, but this is impossible to replicate.

**Comment by TheKevJames** [comment]
Note to self: previous commit has too many versions. Amend to include only most recent supported travis version for rvm 2.x (est. Jan 19th given how slow Travis picks up tests)

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c91a29bef0f2bc0c975ab9df3cd7f060892f1264
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 4a3cee210e10f7c31de84324d0c80207a9b396dc
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: d93ed548c8e4a3a5d65b8e2162bd871458ec049f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thekevjames/puppet-homebrew

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: c91a29bef0f2bc0c975ab9df3cd7f060892f1264
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 4a3cee210e10f7c31de84324d0c80207a9b396dc
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

 * Commit: d93ed548c8e4a3a5d65b8e2162bd871458ec049f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 623c7c6a04037d22d7e208717143f0fb8a2dddd9
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/thekevjames/puppet-homebrew

---
This message was auto-generated by https://gitcop.com

**Pull request merged**
