### PR TITLE
Fix for brewcask not working due brew cask list --versions

### PR DESCRIPTION
**Pull request by jordigg**
Fix for making brewcask actually work. Error caused by `brew cask list --versions` and bad parsing of the results as explained on issue #2.

Parsing `brew cask list --versions` results like we do with brew seems to have fixed the problem. Work on my test and prod environment.

### CODE REVIEW

**Comment by TheKevJames** [comment]
Thanks for the issue report and bugfix! Leaving a not for myself that #1 needs to take this change into account, when I get around to fixing #1. 

Would you mind updating `lib/puppet/provider/package/homebrew.rb:33` with the same fix?

**Comment by jordigg** [comment]
PR updated with the requested changes.

**Comment by TheKevJames** [comment]
Hmm, I'm having some trouble with this PR: it seems to break things for me. Would you mind pasting the output of running the following commands on your machine (feel free to obscure package names / use different packages than me)?

    $ brew --version
    Homebrew 0.9.5 (git revision 610b; last commit 2016-03-07)
    $ brew cask --version
    0.60.0 (git revision 2a865a; last commit 41 minutes ago)
    $ brew list --versions | head -n1
    ack 2.14
    $ brew list --versions ack
    ack 2.14
    $ brew cask list --versions | head -n1
    clementine 1.2.2
    $ brew cask list --versions clementine
    ==> App Symlinks managed by brew-cask:
    ~/'Applications/clementine.app' -> '/opt/homebrew-cask/Caskroom/clementine/1.2.2/clementine.app'
    ==> Staged content:
    /opt/homebrew-cask/Caskroom/clementine/1.2.2 (794 files)

As you can see, my `brew cask list --versions <NAME>` output does not work with this PR, as `result` is expected to be a variable of the form `NAME VE.RS.ION` à la output of `brew list --versions <NAME>`.

**Comment by jordigg** [comment]
My fault then. Here my results:

```
$ brew --version
Homebrew 0.9.5 (no git repository)
$ brew cask --version
0.60.0 (git revision 98fe; last commit 16 hours ago)
$ brew list --versions | head -n1
gdbm 1.11
$ brew list --versions python
python 2.7.11
$ brew cask list --versions | head -n1
cmake 3.4.3
$ brew cask list --versions cmake
==> App Symlinks managed by brew-cask:
==> Binary Symlinks managed by brew-cask:
'/usr/local/bin/cmake' -> '/opt/homebrew-cask/Caskroom/cmake/3.4.3/CMake.app/Contents/bin/cmake'
'/usr/local/bin/ccmake' -> '/opt/homebrew-cask/Caskroom/cmake/3.4.3/CMake.app/Contents/bin/ccmake'
'/usr/local/bin/cmakexbuild' -> '/opt/homebrew-cask/Caskroom/cmake/3.4.3/CMake.app/Contents/bin/cmakexbuild'
'/usr/local/bin/cpack' -> '/opt/homebrew-cask/Caskroom/cmake/3.4.3/CMake.app/Contents/bin/cpack'
'/usr/local/bin/ctest' -> '/opt/homebrew-cask/Caskroom/cmake/3.4.3/CMake.app/Contents/bin/ctest'
'/usr/local/bin/cmake-gui' -> '/opt/homebrew-cask/Caskroom/cmake/3.4.3/CMake.app/Contents/bin/cmake-gui'
==> Staged content:
/opt/homebrew-cask/Caskroom/cmake/3.4.3 (4337 files)
```

I get exactly the same output as you. Sorry about that, I'm new to Puppet, Brew, etc...
I think the errors comes from `brew list --versions` returning nothing when is empty and `brew cask list --versions` returning `Warning: nothing to list` when there's nothing to list. Will try another fix.

**Pull request closed without merging**
