### PR TITLE
Update facts to work in puppet 3 or 4

### PR DESCRIPTION
**Pull request by edestecd**
I'm still getting this warning in puppet 4, despite having command line tools installed.
```warning('No Command Line Tools detected and no download source set. Please set download sources or install manually.')```

I think puppet 4 is casting the strings to actual booleans and thus not matching the if == "true".
These changes should make the facts behave more predictably and work in either puppet 3 or 4.

### CODE REVIEW

**Comment by TheKevJames** [comment]
Hey there! Thanks for the PR -- I'm currently working on trying to get the testing working properly on this repo, but will take a look at this as soon as that's a bit more settled.

**Comment by edestecd** [comment]
I've pushed another commit that makes the has_compiler fact work correctly in 10.10 and up

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 162404a5c40010382f90edf045699edc17a423d8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: e21ec65f14faa596fdf801b78945ee9f64138221
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thekevjames/puppet-homebrew

---
This message was auto-generated by https://gitcop.com

**Comment by TheKevJames** [comment]
Hey there! Sorry this sat around for so long; those test failures have been a nightmare. Thanks for the PR, looks great.

**Pull request merged**
