### PR TITLE
style(inheritance): remove provider inheritance

### LINKED ISSUE #72: Error: Failed to apply catalog: No command brew defined for provider brew
I continue having the following error intermittently on new systems:
`Error: Failed to apply catalog: No command brew defined for provider brew`

I'm not sure what is causing this error to appear on some new system and not on some others. I can confirm that if `brew` is already present before puppet runs the problem will disappear. May be related to the random order that puppet runs every time is executed.

The only way I've found to fix this issue is adding the following line
`commands :brew => '/usr/local/bin/brew'` 
into https://github.com/TheKevJames/puppet-homebrew/blob/master/lib/puppet/provider/package/brew.rb

This shouldn't interfere with anything else, so I would suggest adding it in order to get rid of this random errors. What do you say @TheKevJames?

### PR DESCRIPTION
**Pull request by TheKevJames**
Fuck DRY, `brewcommon` seems to be causing issues.

Fixes #72 and #73

### CODE REVIEW

**Comment by TheKevJames** [comment]
@jordigg I'd like to cut a new release after merging this PR, but I neither currently have a Mac nor trust the still-broken test suite. Could you checkout this branch and check to make sure everything seems to work?

**Comment by jordigg** [comment]
I can help with that but tests are still flaky and have no idea why. I just happens randomly with commands that should just work...

**Comment by jordigg** [comment]
I can confirm everything works as expected.

**Comment by TheKevJames** [comment]
Thanks a bunch! I still wish we could figure out the tests, but in the meantime, I'll release this.

**Pull request merged**
