### PR TITLE
brew: install correctly on apple silicon

### PR DESCRIPTION
**Pull request by damonbreeden**
`brew` expects to see files in `/opt/homebrew` on Apple silicon so check for that and set the paths accordingly

### CODE REVIEW

**Review by TheKevJames — APPROVED** [review]
Looks great to me! Thanks for tackling this. :)

**Comment by sp-ricard-valverde** [comment]
Late to the party, but seems that `$::facts[processors][models]` is not always available.
I've found the issue when running on GitHub CI macOS workers but I can reproduce the same locally(`processor` fact has no `modules` key)

**Comment by TheKevJames** [comment]
@sp-ricard-valverde shoot. Anything special about those systems? Or perhaps any other keys in `processor` we might be able to fall back to checking?

**Comment by sp-ricard-valverde** [comment]
Nothing special that I could see. It may be related to OS permissions, Full Disk Access, ... dunno.
I ended up successfully implementing the `has_arm64` fact from PR #154 as processors did not contain relevant information.
There are already facts regarding architecture though(with values `x86_64`, `arm64`) that seem to be pretty reliable.

**Pull request merged**
